### ISSUE TITLE
Documentation unclear about what the `device_name` is exactly

### ISSUE THREAD

**Issue by PronkMedia** [ollo69/ha_tuya_custom#21]
Hi, I'm using this repo/integration since 2 weeks and I'm really happy with the efforts to fix the current Tuya integration issues. Thanks for that!

From the documentation it's not really clear what I have to enter as `device_name` when providing custom device information via configuration.yaml, in my understanding it should be one of these, but I'm not sure which is correct:
- Full sensor name, eg: `light.kitchen`
- Sensor name without domain, eg: `kitchen`
- Friendly name, eg `KitchenLight`

Could you please clarify on this topic and maybe update the documentation?

**Comment by ollo69** [comment]
You must use Friendly Name or "tuya_device_id" that is exposed with a specific entity attribute.
I will update documentation as soon as I will have some time.

**Comment by DukeNuken** [comment]
I have the same problem with "device_name". I have a switcher with 3 buttons. So what "device_name" should be the name of the main switcher or of each button? Where those names should came from? from Tuya mobile application?

**Comment by PronkMedia** [comment]
Thank you for clarifying this!
