### ISSUE TITLE
Tuya error in HA logs

### ISSUE THREAD

**Issue by gsksim** [ollo69/ha_tuya_custom#42]
Logger: custom_components.tuya_custom
Source: custom_components/tuya_custom/__init__.py:431
Integration: Tuya Custom (documentation)
First occurred: 2:46:13 PM (3 occurrences)
Last logged: 2:51:13 PM

Method [QueryDevice] for device ebb47b582f8112591ai6kq fails using poll interval 60.0 - error: you can query once in 120 seconds

**Comment by ollo69** [comment]
This is a Warning due to the fact that Tuya increase poll interval limits (you can query once in 120 seconds). You can adjust query and discovery poll interval using the component options in available in integration page.

**Comment by albanleandri** [comment]
> This is a Warning due to the fact that Tuya increase poll interval limits (you can query once in 120 seconds). You can adjust query and discovery poll interval using the component options is available on the integration page.

Hi @ollo69, I encounter the same issue, could you please provide an example of configuration to make the adjustment mentioned? My system seems to be polling too often, but the extension doc does not mention explicitly how to work it around.
Thanks

**Comment by ollo69** [comment]
The poll interval is available as HA options in the integration page.
But with HA v118.0 all feature of this custom component was released in standard Tuya component and all devices specific options are also available through UI, so I suggest to come back to standard.

**Comment by gsksim** [comment]
Thanks for the update
