### ISSUE TITLE
Get accesstoken failed

### ISSUE THREAD

**Issue by silverStSt** [ollo69/ha_tuya_custom#43]
I went from Tuya component to tuya_custom a few days ago and it initially worked great, but since yesterday I can't connect to the account and I got a Get accesstoken failed error.  Username or password error.  I have verified the username and password and it is correct.  I have reinstalled the Tuya component, and it works fine.

**Comment by ollo69** [comment]
Tuya Custom and standard Tuya use the same API to connect to Tuya, so if one work also the other must work.
Remember that you must remove standard integration before using custom_tuya or will create a conflict.
If you still have error please post here your HA log, otherwise I cannot help.

**Comment by silverStSt** [comment]
I have erased everything and started from scratch and it has worked.  something would have been corrupted, thank you very much.
