### ISSUE TITLE
Incorrect Readings on Thermostat

### ISSUE THREAD

**Issue by sicXnull** [ollo69/ha_tuya_custom#46]
Using a Sasswell (Tuya) thermostat

It appears to be showing Celsius as Fahrenheit, and it's also doubled. I've tried some of the known "Fixes" for this error but that does not appear to work out. 

Halving current temp is 22.25 Celsius which is the correct temp in the house (72 F)

Looks like the math needs changed here to - (Current temp /2)× 9/5) + 32 as a dirty fix. I'm sure there's a better way to do it though. 
 
![image](https://user-images.githubusercontent.com/31908995/96376923-c2030b00-114f-11eb-89e3-366f8f760007.png)

**Comment by ollo69** [comment]
Did you read the [repository readme](https://github.com/ollo69/ha_tuya_custom/blob/master/README.md)?
You should set `unit_of_measurement` and `temp_divider` to fix this.
If looks too complex to you manage `configuration.yaml`, be patient and wait for fix implementation in standard Tuya component that will allow to change parameter using UI.

**Comment by sicXnull** [comment]
tbh no, noob moment. Found the repo and installed it. I will work with those.

**Comment by sicXnull** [comment]
Changes don't seem to work. Pulled debug

```2020-10-19 20:44:58 DEBUG (SyncWorker_52) [custom_components.tuya_custom.tuyaha.tuyaapi] Tuya request response: {'payload': {'data': {'current_temperature': 692, 'min_temper': 50, 'temperature': 700, 'max_temper': 950, 'online': True, 'state': 'true'}}, 'header': {'code': 'SUCCESS', 'payloadVersion': 1}}```

**Comment by ollo69** [comment]
What does not work? What is your configuration?

**Comment by sicXnull** [comment]
No change in temp. Should be showing 72 F or at the very least 22 C. Changing divider / unit_of_measurement is not changing anything.  

![image](https://user-images.githubusercontent.com/31908995/96527205-98300e00-124d-11eb-82d4-09df79902cd6.png)

```
tuya_custom:
  devices_config:
    - device_name: Home Thermostat
      unit_of_measurement: F
      temp_divider: 2
      curr_temp_divider: 2

**Comment by ollo69** [comment]
Are you sure that name is "Home Thermostat"? Can you show me device page?

**Comment by sicXnull** [comment]
Nice - That fixed it kinda. 

Just needs decimal now. (Ex 69.2 F)

![image](https://user-images.githubusercontent.com/31908995/96528045-ada63780-124f-11eb-8f0d-b5ce1d2ecace.png)

**Comment by ollo69** [comment]
temp_divider: 10

**Comment by sicXnull** [comment]
There it is! Thanks for the help
