### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by David8867** [ollo69/ha_tuya_custom#47]
Hello,

Sorry for the question, but I am not sure how to configure the integration: is there a popup windows also like the Tuya integration to get data from the Cloud? If yes, I do not see how to do it? (see attachment)
![2020-10-22 14_32_09-HACS - Home Assistant](https://user-images.githubusercontent.com/71266856/96872131-8039d380-1473-11eb-9428-ebdca6a1814f.png)

Thank you,

Kr,

David.

**Comment by ollo69** [comment]
Once installed you must go in the integration page, press + and search for Tuya_Custom. Same process used to configure standard Tuya.

**Comment by David8867** [comment]
Hi,
I've restarted once more HA but I can not find tuya_Custon, only Tuya.
Tuya_Custom is well present in Custom_Components folder...
Kr,
David.
    Le jeudi 22 octobre 2020 à 14:40:43 UTC+2, ollo69 <notifications@github.com> a écrit :  
 
 


Once installed you must go in the integration page, press + and search for Tuya_Custom. Same process used to configure standard Tuya.

**Comment by ollo69** [comment]
Clear your browser cache

**Comment by David8867** [comment]
Well spotted :-) !!
thank you very much.
Kr,
David.
    Le jeudi 22 octobre 2020 à 15:29:54 UTC+2, ollo69 <notifications@github.com> a écrit :  
 
 


Clear your browser cache
