### ISSUE TITLE
I don't see Light options under Integration->Tuya Custom -> Options 

### ISSUE THREAD

**Issue by JPCoollink** [ollo69/ha_tuya_custom#52]
I can't find anywhere to set the specified light options. 
There is no such options under Integration->Tuya Custom -> Options . 
Neither under each device or entity.

**Comment by ollo69** [comment]
Specific option is shown only if you have light? Are your devices detected as light?

**Comment by JPCoollink** [comment]
Yes

**Comment by ollo69** [comment]
Please provide some screen-shot of options pages

**Comment by JPCoollink** [comment]
![image](https://user-images.githubusercontent.com/21026754/103462604-6844c280-4cf4-11eb-9543-f94928985d90.png)
![image](https://user-images.githubusercontent.com/21026754/103462619-7bf02900-4cf4-11eb-93cd-00b2eebd1b2e.png)
![image](https://user-images.githubusercontent.com/21026754/103462630-8ca09f00-4cf4-11eb-92eb-f7c87edfe5e1.png)
![image](https://user-images.githubusercontent.com/21026754/103462643-9fb36f00-4cf4-11eb-92bc-eba82f270968.png)

**Comment by ollo69** [comment]
In the list highlighted below you should have the list of your lights.
Select them and click submit to open the configuration page.

![image](https://user-images.githubusercontent.com/60491700/103468390-e2a72e00-4d58-11eb-93bf-455f6bb20927.png)

**Comment by JPCoollink** [comment]
Working now, I didn't know how to use the options tab. 
I suggest you add this in the Wiki. 
Any how, thanks for the support !
