### ISSUE TITLE
re Oliver Invalid Add-on repository!

### ISSUE THREAD

**Issue by oliverchapple** [ollo69/ha_tuya_custom#56]
hi 

you have some wrong with this link because it comes up with https://github.com/ollo69/ha_tuya_custom its says Invalid Add-on repository! 

I don.t know why that is 

thanks Oliver

**Comment by ollo69** [comment]
Who says "Invalid Add-on repository"?

**Comment by oliverchapple** [comment]
[
![Screenshot 2021-02-12 at 23 29 15](https://user-images.githubusercontent.com/42448591/107833163-4ece7600-6d8a-11eb-8ac2-043a7d6a075f.png)
](url)


home assistant says it 

thanks

**Comment by ollo69** [comment]
This is an integration, not an Add-on.

**Comment by ollo69** [comment]
Closed because not an issue
